server:
  port: 8080

spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:

        - id: user-service
          uri: lb://revshop-user-service
          predicates:
            - Path=/auth/**,/user/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**,/categories/**,/reviews/**,/favorites/**

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
      prefer-ip-address: true

